use_frameworks!

target 'HiliteUI_Example' do
  pod 'HiliteUI', :path => '../'

  pod 'HiliteCore', '~> 0.1.20-alpha'

  target 'HiliteUI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
